feat: add getGsos function
Dual-Finance/gso-sdk pull request #23
Opened 2023-04-25 20:00 UTC by diegofigs

2023-04-25 20:42 UTC, brittcyr commented on src/gso.ts
> +    // eslint-disable-next-line no-restricted-syntax
put this in eslintrc

2023-04-25 20:42 UTC, brittcyr commented on src/gso.ts
> +    const soOptionMint = await so.soMint(
why all these formatting changes? not a problem, but not necessary. if you want to do all these changes, generally should be doing them in a separate pull request.

2023-04-25 20:42 UTC, brittcyr commented on src/gso.ts
> +        // eslint-disable-next-line no-continue
eslintrc

2023-04-25 20:42 UTC, brittcyr commented on src/gso.ts
> +      // TODO: Unroll these and cache the fetches to improve page load.
copy pasta?

2023-04-25 20:42 UTC, brittcyr commented on src/utils.ts
> +export function readBigUInt64LE(buffer: Buffer, offset = 0) {
copy pasta? fix dependency like I fixed in dip sdk

2023-04-25 20:42 UTC, brittcyr commented on package.json
>      "prebuild": "yarn clean",
Need to bump the version

2023-04-25 20:42 UTC, brittcyr commented on jest.config.js
> +/** @type {import('ts-jest').JestConfigWithTsJest} */
add a github action to run the test

2023-04-25 20:42 UTC, brittcyr commented on src/gso.ts
> +        || lockupRatio <= 0
Why do we have checks for lockupRatio and strike?

2023-04-25 20:42 UTC, brittcyr commented on src/utils.ts
> +export function parseGsoState(buf: Buffer) {
space between functions?

2023-04-25 20:42 UTC, brittcyr commented on src/gso.ts
> +export const GSO_STATE_SIZE = 1000;
Dont need to export this, it is an internal implementation detail

2023-04-25 20:42 UTC, brittcyr commented on src/gso.ts
> +      if (acct.account.data.length !== GSO_STATE_SIZE) {
Is this redundant with the gpa filter?

2023-04-25 20:42 UTC, brittcyr commented on tests/gso.test.ts
> +    console.info(gsos);
Dont log this, should be big and spammy

2023-04-25 20:42 UTC, brittcyr commented on tests/gso.test.ts
> +      expect(Number(gso.expiration) * 1000).toBeGreaterThan(Date.now());
The filtering in the code is for subscription period end, not expiration. The fact that subscription <= expiration is an implementation detail that while it should be safe, isnt guaranteed in the client implementation

2023-04-25 20:42 UTC, brittcyr commented on src/gso.ts
> +  public async getGsos(): Promise<GsoParams[]> {
Document the function. Ideally higher quality like in the dip-sdk functions

2023-04-28 01:17 UTC, DonDuala approved these changes

2023-04-28 22:01 UTC, brittcyr requested changes

2023-04-28 22:01 UTC, brittcyr commented on .github/workflows/ci.yml
> +  push:
and on demand

2023-05-01 18:39 UTC, brittcyr commented on .github/workflows/ci.yml
> +        run: yarn lint
Split them out. There is no good reason to have them merged like this and it just breaks the pattern we have in other repos.

2023-05-01 18:41 UTC, brittcyr commented on package.json
> +  "version": "0.1.0",
Stay consistent with the patterns in the codebases that you are working in. Only break from the patterns when there is a good reason which I dont see here.

2023-05-01 19:13 UTC, brittcyr commented on .github/workflows/ci-lint.yml
> +name: Node.js CI
Can keep the name lint

2023-05-01 19:13 UTC, brittcyr commented on src/gso.ts
> +  strike: number;
strike is an SO field

2023-05-01 19:13 UTC, brittcyr commented on src/gso.ts
> +  publicKey: PublicKey;
publicKey for what? the gso state?

2023-05-01 19:13 UTC, brittcyr commented on src/utils.ts
> +/* eslint-disable import/prefer-default-export */
is this needed?

2023-05-01 19:13 UTC, brittcyr commented on tests/gso.test.ts
> +    process.env.RPC_URL || clusterApiUrl('devnet'),
default to mainnet since gso is stuck in governance on devnet, also because BONK on devnet isnt a thing

2023-05-01 19:13 UTC, brittcyr commented on tests/gso.test.ts
> +    'confirmed',
why are you only testing confirmed here instead of the default finalized?

2023-05-01 19:13 UTC, brittcyr commented on tests/gso.test.ts
> +    expect(gsos.length).toBeGreaterThanOrEqual(1);
How are you currently testing this? It should be failing on mainnet right now without any gso active

2023-05-01 19:13 UTC, brittcyr commented on src/gso.ts
> +    const data = await connection.getProgramAccounts(GSO_PK, {
choose a better variable name than data

2023-05-01 19:13 UTC, brittcyr commented on src/gso.ts
> +    for (const acct of data) {
what is acct? call it something more descriptive like gsoStateAccount

2023-05-01 19:13 UTC, brittcyr commented on src/gso.ts
> +        stakeTimeRemainingMs <= 0
does this not fit on one line?

2023-05-01 19:14 UTC, brittcyr commented on tests/gso.test.ts
> +    'confirmed',
fine if there is a reason, just curious

2023-05-01 20:58 UTC, brittcyr commented on tests/gso.test.ts
> +    process.env.RPC_URL || clusterApiUrl('devnet'),
If this blocks submission since we don't have any active gso, just switch back and leave a comment.

2023-05-01 23:01 UTC, brittcyr approved these changes

2023-05-01 23:01 UTC, brittcyr commented on src/gso.ts
> +  publicKey: PublicKey;
Note that in the variable name. Should be obvious from reading exactly what it is

2023-05-02 00:22 UTC, brittcyr commented on .env.example
> +RPC_URL=https://rpc.helius.xyz/?api-key=e330d9d4-5acc-4260-a760-c80d7bab7d6c
Is this protected? do not check it in if there is a quota associated with it, just use the public one

2023-05-02 02:50 UTC, merged